### ISSUE TITLE
Wrong Tools

### ISSUE THREAD

**Issue by Insane96** [Insane96/IguanaTweaksReborn#139]
Disabled by default

- [ ] Breaking a block that needs a tool with a fist will deal damage to the player as block_hardness * multiplier.
- [ ] Breaking a block with the wrong tool (diamond ore with stone pickaxe or planks with a shovel) will destroy the tool. If unbreaking is preset then the tool has has chance (based on Unbreaking) to not break, but still the block will not be mined

**Comment by Darkorg69** [comment]
Is this feature implemented or it is still WIP?

**Comment by Insane96** [comment]
Not yet implemented

**Comment by Darkorg69** [comment]
I've been making a new modpack lately to play with friends and it's realism based. I'm desperately searching for a mod that can disable wood breaking with hand. I have been told to use NoTreePunching, but the mod also adds tons of other things that are incompatible with my modpack. Would love to see this feature implemented in this mod, since I'm already using it and it will make my pack complete.
